### ISSUE TITLE
post note on qiime forum that qiime-help@colorado.edu is no longer monitored

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/qiime#1866]
and make sure that all docs use the gmail address, if it's used anywhere

**Comment by gregcaporaso** [comment]
Done:
https://groups.google.com/d/msg/qiime-forum/5tmvGNjh9Aw/SJ_c9A6jyZ8J

**Comment by adamrp** [comment]
Does the qiime-help@colorado.edu account still exist? If so, it would be good to give it an auto-reply indicating that it is no longer monitored.
